modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/TeamTwilight/twilightforest/issues"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="twilightforest:twilight_portal_miniature_structure"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest"
updateJSONURL="https://gh.tamaized.com/TeamTwilight/twilightforest/update.json"
logoFile="twilightforest_logo.png"
credits="By Benimatic (Ben Mazur)"
authors="${mod_authors}"
description='''
An enchanted forest dimension.
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[modproperties.${mod_id}]
    configuredBackground="twilightforest:textures/block/mazestone_large_brick.png"